services:
  postgres:
    image: postgres:16-alpine
    container_name: slooze-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: slooze_food_ordering
    ports:
      - "5432:5432"
    volumes:
      - slooze_postgres_data:/var/lib/postgresql/data

volumes:
  slooze_postgres_data:
